// models/Application.js
const mongoose = require('mongoose');

const applicationSchema = new mongoose.Schema(
  {
    jobId: { type: mongoose.Schema.Types.ObjectId, ref: 'Job', required: true },
    candidateId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    status: {
      type: String,
      enum: ['Applied', 'Interviewing', 'Rejected', 'Offer'],
      default: 'Applied',
    },
    resumeUrl: { type: String }, // will hold URL to uploaded PDF resume
    aiMatchScore: { type: Number, min: 0, max: 100 }, // score from AI microservice
    adaptiveInterviewLink: { type: String }, // link generated by AI service
  },
  { timestamps: true }
);

// Compound index for fast Kanban board queries
applicationSchema.index({ jobId: 1, status: 1 });

module.exports = mongoose.model('Application', applicationSchema);
